// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: service_message.proto

package talk

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServiceQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question string `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
}

func (x *ServiceQuestion) Reset() {
	*x = ServiceQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceQuestion) ProtoMessage() {}

func (x *ServiceQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceQuestion.ProtoReflect.Descriptor instead.
func (*ServiceQuestion) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type ServiceAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ServiceAnswer) Reset() {
	*x = ServiceAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAnswer) ProtoMessage() {}

func (x *ServiceAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_service_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAnswer.ProtoReflect.Descriptor instead.
func (*ServiceAnswer) Descriptor() ([]byte, []int) {
	return file_service_message_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceAnswer) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_service_message_proto protoreflect.FileDescriptor

var file_service_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x38, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x61,
	0x6c, 0x6b, 0x12, 0x29, 0x0a, 0x03, 0x41, 0x73, 0x6b, 0x12, 0x10, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x61, 0x6c, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_message_proto_rawDescOnce sync.Once
	file_service_message_proto_rawDescData = file_service_message_proto_rawDesc
)

func file_service_message_proto_rawDescGZIP() []byte {
	file_service_message_proto_rawDescOnce.Do(func() {
		file_service_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_message_proto_rawDescData)
	})
	return file_service_message_proto_rawDescData
}

var file_service_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_message_proto_goTypes = []interface{}{
	(*ServiceQuestion)(nil), // 0: ServiceQuestion
	(*ServiceAnswer)(nil),   // 1: ServiceAnswer
}
var file_service_message_proto_depIdxs = []int32{
	0, // 0: ServiceTalk.Ask:input_type -> ServiceQuestion
	1, // 1: ServiceTalk.Ask:output_type -> ServiceAnswer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_message_proto_init() }
func file_service_message_proto_init() {
	if File_service_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_message_proto_goTypes,
		DependencyIndexes: file_service_message_proto_depIdxs,
		MessageInfos:      file_service_message_proto_msgTypes,
	}.Build()
	File_service_message_proto = out.File
	file_service_message_proto_rawDesc = nil
	file_service_message_proto_goTypes = nil
	file_service_message_proto_depIdxs = nil
}
